# Generated by Django 4.2.7 on 2023-11-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_question_correct_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='time_limit',
            field=models.IntegerField(choices=[(10, 10), (20, 20), (30, 30), (40, 40), (50, 50)], default=30),
        ),
    ]
