# Generated by Django 4.2.7 on 2023-11-10 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_question_time_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='qn_no',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
