# Generated by Django 4.2.7 on 2023-11-12 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_alter_option_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='quiz',
        ),
    ]
