# Generated by Django 4.2.7 on 2023-11-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_question_attempt_time_taken_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question_attempt',
            name='time_taken',
        ),
        migrations.AddField(
            model_name='question_attempt',
            name='time_left',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
