# Generated by Django 4.2.7 on 2023-11-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_remove_question_attempt_time_taken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_attempt',
            name='option_chosen',
            field=models.IntegerField(default=-1),
        ),
    ]
