# Generated by Django 4.2.7 on 2023-11-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_alter_question_attempt_option_chosen'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz_attempt',
            name='time_left',
            field=models.DecimalField(decimal_places=2, default=60.0, max_digits=10),
        ),
    ]
