# Generated by Django 4.2.7 on 2023-11-25 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0020_quiz_attempt_time_left'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz_attempt',
            name='time_left',
        ),
    ]
